[phases.setup]
nixPkgs = ["jdk17"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[start]
cmd = "java -Xmx400m -Xms200m -Dserver.port=$PORT -jar target/construccion-backend-1.0.0.jar --spring.profiles.active=railway"
